commerce_payment.commerce_payment_gateway.plugin.bambora_custom_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    payments_api_key:
      type: string
      label: 'Payments API Key'
    profiles_api_key:
      type: string
      label: 'Profiles API Key'
